## Codewars Autograder
Vitor Gonçalves
vgoncalves@usn.org

---

> Note: Need to add ability to take in CSV files of the student's usernames </br>
> Note: Need to add ability to grade certain codewars id's

procedure:
1. get list of students usernames in a CSV file
2. get list of codewars ids assigned in a CSV file, id, name, number of points
3. create a function that can grade a single question to each user
4. add pandas columns to those questions, either a true or false from the function
5. create a function that reads each test question column and grades it in a new column
6. add input to that function that only shows the grade or the 

---
link: https://dev.codewars.com/#get-user

In [1]:
import requests
import pandas as pd

## IMPORT CSV

link: https://sparkbyexamples.com/pandas/pandas-read-excel-multiple-sheets-in-pandas/

## USER SUMMARY FUNCTIONS

In [52]:
def getSummaryResponse(user):
    #INPUT: string of the student's username
    #OUTPUT: API Response from the codewars website, user's summary
    
    response = requests.get(f"https://www.codewars.com/api/v1/users/{user}")
    return response

In [50]:
def readUserSummary(response):
    #INPUT: Https response from codewars
    #OUTPUT: PANDAS Dataframe containing the information we can about
    
    #creates the required columns from codewars
    name = response.json()["name"]
    user = response.json()["username"]
    pyrank = response.json()['ranks']["languages"]["python"]["rank"]
    pyscore = response.json()['ranks']["languages"]["python"]["score"]
    completed = response.json()['codeChallenges']['totalCompleted']
    
    return pd.DataFrame({"Name": [name],
                         "User": [user],
                        "Rank": [pyrank],
                        "Score": [pyscore],
                        "Completed": [completed]})

In [57]:
def printClassSummary(list_of_students):
    #INPUT: pd Series containing the list of their usernames
    #OUTPUT: pd DataFrame with students organized by score and number of kata they have completed
    students = pd.DataFrame({
            "Name": [],
            "User": [],
            "Rank": [],
            "Score": [],
            "Completed": []
        })
    for i in list_of_students:
        new_data = readUserSummary(getSummaryResponse(i))
        students = pd.concat([students,new_data],ignore_index=True)
    return students.sort_values(by=['Score','Completed'],ascending=False)

## USER CHALLENGE FUNCTIONS

In [46]:
def getChallengeResponse(user, page = 0):
    #INPUT: string of the student's username
    #OUTPUT: API Response from the codewars website, list of completed challenges
    
    response = requests.get(f"https://www.codewars.com/api/v1/users/{user}/code-challenges/completed?page={page}")
    
    return response

In [44]:
def checkChallenge(username, assignmentid):
    #INPUT: string of the username, string of the assignment id
    #OUTPUT: Boolean on the result of the search
    
    kataPages = getChallengeResponse(username).json()["totalPages"]
    print(type(kataPages))
    
    for page in range(kataPages):
        challengeList = getChallengeResponse(username, page).json()["data"]
        for kata in challengeList:
            if kata["id"] == assignmentid:
                return (kata["name"], True)
    return (kata["name"], False)

In [45]:
checkChallenge("Captain Quack", "50654ddff44f800200000004")

<class 'int'>

('Multiply', True)

In [ ]:
def readUserCompleted(response):
    pass

In [19]:
getChallengeResponse("Captain Quack",1).json()

# default id multiply: 50654ddff44f800200000004

{'totalPages': 2,
 'totalItems': 296,
 'data': [{'id': '5f882dcc272e7a00287743f5',
   'name': '[Code Golf] Return Odd No Matter What',
   'slug': 'code-golf-return-odd-no-matter-what',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-22T19:07:16.852Z'},
  {'id': '52a382ee44408cea2500074c',
   'name': 'Matrix Determinant',
   'slug': 'matrix-determinant',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-21T22:45:32.508Z'},
  {'id': '59a96d71dbe3b06c0200009c',
   'name': 'Build a square',
   'slug': 'build-a-square',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-21T01:31:47.392Z'},
  {'id': '56b1f01c247c01db92000076',
   'name': 'Double Char',
   'slug': 'double-char',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-20T13:33:17.978Z'},
  {'id': '55cbc3586671f6aa070000fb',
   'name': 'Grasshopper - Check for factor',
   'slug': 'grasshopper-check-for-factor',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-19T23:57:45.606Z'},
  {'id': '55cb854deb36f11f130000e1',
   'name': 'Grasshopper - Debug',
   'slug': 'grasshopper-debug',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-19T23:56:17.614Z'},
  {'id': '55ca77fa094a2af31f00002a',
   'name': 'Grasshopper - Messi Goals',
   'slug': 'grasshopper-messi-goals',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-19T23:50:15.692Z'},
  {'id': '540c33513b6532cd58000259',
   'name': 'Sum of all arguments',
   'slug': 'sum-of-all-arguments',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-19T13:15:53.890Z'},
  {'id': '515e271a311df0350d00000f',
   'name': 'Square(n) Sum',
   'slug': 'square-n-sum',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-19T13:06:46.889Z'},
  {'id': '5993fb6c4f5d9f770c0000f2',
   'name': 'Sum a list but ignore any duplicates',
   'slug': 'sum-a-list-but-ignore-any-duplicates',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-18T20:32:45.445Z'},
  {'id': '5254ca2719453dcc0b00027d',
   'name': 'So Many Permutations!',
   'slug': 'so-many-permutations',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-18T19:54:16.581Z'},
  {'id': '541c8630095125aba6000c00',
   'name': 'Sum of Digits / Digital Root',
   'slug': 'sum-of-digits-slash-digital-root',
   'completedLanguages': ['python', 'csharp'],
   'completedAt': '2022-09-18T03:45:12.611Z'},
  {'id': '59a1cdde9f922b83ee00003b',
   'name': 'Stanton measure',
   'slug': 'stanton-measure',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-17T19:23:09.906Z'},
  {'id': '5813d19765d81c592200001a',
   'name': "Don't give me five!",
   'slug': 'dont-give-me-five',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-17T19:12:37.112Z'},
  {'id': '57a6633153ba33189e000074',
   'name': 'Ordered Count of Characters',
   'slug': 'ordered-count-of-characters',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-16T15:11:25.718Z'},
  {'id': '57a60bad72292d3e93000a5a',
   'name': 'Make acronym',
   'slug': 'make-acronym',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-16T14:54:22.606Z'},
  {'id': '57eadb7ecd143f4c9c0000a3',
   'name': 'Abbreviate a Two Word Name',
   'slug': 'abbreviate-a-two-word-name',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-16T00:20:39.101Z'},
  {'id': '56cd44e1aa4ac7879200010b',
   'name': 'Is the string uppercase?',
   'slug': 'is-the-string-uppercase',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-16T00:17:40.752Z'},
  {'id': '54e6533c92449cc251001667',
   'name': 'Unique In Order',
   'slug': 'unique-in-order',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-16T00:08:30.634Z'},
  {'id': '57d814e4950d8489720008db',
   'name': 'N-th Power',
   'slug': 'n-th-power',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-15T23:53:40.998Z'},
  {'id': '57ec8bd8f670e9a47a000f89',
   'name': 'The Wide-Mouthed frog! ',
   'slug': 'the-wide-mouthed-frog',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-15T17:10:12.217Z'},
  {'id': '5572f7c346eb58ae9c000047',
   'name': 'Complete The  Pattern #1 ',
   'slug': 'complete-the-pattern-number-1',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-14T19:10:03.524Z'},
  {'id': '57f780909f7e8e3183000078',
   'name': 'Beginner - Reduce but Grow',
   'slug': 'beginner-reduce-but-grow',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-14T00:26:27.116Z'},
  {'id': '5513795bd3fafb56c200049e',
   'name': 'Count by X',
   'slug': 'count-by-x',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-13T17:56:11.488Z'},
  {'id': '546f922b54af40e1e90001da',
   'name': 'Replace With Alphabet Position',
   'slug': 'replace-with-alphabet-position',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-13T16:29:55.305Z'},
  {'id': '5727bb0fe81185ae62000ae3',
   'name': 'Backspaces in string',
   'slug': 'backspaces-in-string',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-13T01:53:01.757Z'},
  {'id': '525f4206b73515bffb000b21',
   'name': 'Adding Big Numbers',
   'slug': 'adding-big-numbers',
   'completedLanguages': ['csharp'],
   'completedAt': '2022-09-12T00:57:41.138Z'},
  {'id': '5265326f5fda8eb1160004c8',
   'name': 'Convert a Number to a String!',
   'slug': 'convert-a-number-to-a-string',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-11T17:40:04.417Z'},
  {'id': '515e188a311df01cba000003',
   'name': 'Get Planet Name By ID',
   'slug': 'get-planet-name-by-id',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-11T17:37:51.944Z'},
  {'id': '54da5a58ea159efa38000836',
   'name': 'Find the odd int',
   'slug': 'find-the-odd-int',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-11T17:36:13.043Z'},
  {'id': '525f50e3b73515a6db000b83',
   'name': 'Create Phone Number',
   'slug': 'create-phone-number',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-11T16:58:55.459Z'},
  {'id': '569e09850a8e371ab200000b',
   'name': 'Pre-FizzBuzz Workout #1',
   'slug': 'pre-fizzbuzz-workout-number-1',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-11T16:34:05.519Z'},
  {'id': '57089707fe2d01529f00024a',
   'name': 'Grasshopper - If/else syntax debug',
   'slug': 'grasshopper-if-slash-else-syntax-debug',
   'completedLanguages': ['python', 'csharp'],
   'completedAt': '2022-09-10T21:40:42.009Z'},
  {'id': '631d001fb80b15d7485cdde2',
   'name': 'Balance of Power',
   'slug': 'balance-of-power',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-10T21:28:58.530Z'},
  {'id': '631bb98b0a30e955035a882a',
   'name': 'Counting Carrots (Intro to Brain****)',
   'slug': 'counting-carrots-intro-to-brain-star-star-star-star',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-10T00:14:20.859Z'},
  {'id': '5a8059b1fd577709860000f6',
   'name': 'Alphabetically ordered ',
   'slug': 'alphabetically-ordered',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-09T20:16:57.229Z'},
  {'id': '586f6741c66d18c22800010a',
   'name': 'Sum of a sequence',
   'slug': 'sum-of-a-sequence',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-09T20:08:23.130Z'},
  {'id': '53dc54212259ed3d4f00071c',
   'name': 'Sum Arrays',
   'slug': 'sum-arrays',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-09T19:59:13.535Z'},
  {'id': '583710ccaa6717322c000105',
   'name': 'Simple multiplication',
   'slug': 'simple-multiplication',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-09T19:58:37.989Z'},
  {'id': '5a2be17aee1aaefe2a000151',
   'name': 'Array plus array',
   'slug': 'array-plus-array',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-09T19:48:53.517Z'},
  {'id': '52597aa56021e91c93000cb0',
   'name': 'Moving Zeros To The End',
   'slug': 'moving-zeros-to-the-end',
   'completedLanguages': ['python', 'cobol'],
   'completedAt': '2022-09-09T19:21:50.021Z'},
  {'id': '5168bb5dfe9a00b126000018',
   'name': 'Reversed Strings',
   'slug': 'reversed-strings',
   'completedLanguages': ['python', 'cfml'],
   'completedAt': '2022-09-09T15:05:48.856Z'},
  {'id': '554b4ac871d6813a03000035',
   'name': 'Highest and Lowest',
   'slug': 'highest-and-lowest',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-07T15:09:00.695Z'},
  {'id': '5761a717780f8950ce001473',
   'name': 'How old will I be in 2099?',
   'slug': 'how-old-will-i-be-in-2099',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-07T00:46:54.931Z'},
  {'id': '55c45be3b2079eccff00010f',
   'name': 'Your order,  please',
   'slug': 'your-order-please',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-07T00:00:51.193Z'},
  {'id': '51f2d1cafc9c0f745c00037d',
   'name': 'String ends with?',
   'slug': 'string-ends-with',
   'completedLanguages': ['python', 'csharp', 'clojure'],
   'completedAt': '2022-09-06T22:36:40.159Z'},
  {'id': '551b4501ac0447318f0009cd',
   'name': 'Convert a Boolean to a String',
   'slug': 'convert-a-boolean-to-a-string',
   'completedLanguages': ['python', 'elixir'],
   'completedAt': '2022-09-06T22:34:54.856Z'},
  {'id': '5601409514fc93442500010b',
   'name': 'How good are you really?',
   'slug': 'how-good-are-you-really',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-04T16:22:45.945Z'},
  {'id': '55908aad6620c066bc00002a',
   'name': 'Exes and Ohs',
   'slug': 'exes-and-ohs',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-04T16:13:03.059Z'},
  {'id': '57eae20f5500ad98e50002c5',
   'name': 'Remove String Spaces',
   'slug': 'remove-string-spaces',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-04T16:02:30.291Z'},
  {'id': '53ee5429ba190077850011d4',
   'name': "You Can't Code Under Pressure #1",
   'slug': 'you-cant-code-under-pressure-number-1',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-04T15:58:22.717Z'},
  {'id': '51c8e37cee245da6b40000bd',
   'name': 'Strip Comments',
   'slug': 'strip-comments',
   'completedLanguages': ['csharp', 'python'],
   'completedAt': '2022-09-04T15:00:58.149Z'},
  {'id': '523b4ff7adca849afe000035',
   'name': 'Function 1 - hello world',
   'slug': 'function-1-hello-world',
   'completedLanguages': ['csharp',
    'python',
    'c',
    'cfml',
    'clojure',
    'cobol',
    'cpp'],
   'completedAt': '2022-09-04T00:48:48.086Z'},
  {'id': '558fc85d8fd1938afb000014',
   'name': 'Sum of two lowest positive integers',
   'slug': 'sum-of-two-lowest-positive-integers',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-03T15:49:14.706Z'},
  {'id': '57a5c31ce298a7e6b7000334',
   'name': 'Bin to Decimal',
   'slug': 'bin-to-decimal',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-03T01:43:04.243Z'},
  {'id': '5a00e05cc374cb34d100000d',
   'name': 'Reversed sequence ',
   'slug': 'reversed-sequence',
   'completedLanguages': ['python'],
   'completedAt': '2022-09-03T01:39:24.188Z'},
  {'id': '555086d53eac039a2a000083',
   'name': 'Opposites Attract',
   'slug': 'opposites-attract',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-30T23:47:54.397Z'},
  {'id': '523f5d21c841566fde000009',
   'name': 'Array.diff',
   'slug': 'array-dot-diff',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-30T18:57:49.695Z'},
  {'id': '520b9d2ad5c005041100000f',
   'name': 'Simple Pig Latin',
   'slug': 'simple-pig-latin',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-30T18:51:39.647Z'},
  {'id': '5412509bd436bd33920011bc',
   'name': 'Credit Card Mask',
   'slug': 'credit-card-mask',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-30T01:11:58.436Z'},
  {'id': '564f458b4d75e24fc9000041',
   'name': "Finding Remainder Without Using '%' Operator",
   'slug': 'finding-remainder-without-using-percent-operator',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-30T00:47:47.455Z'},
  {'id': '55a70521798b14d4750000a4',
   'name': 'Returning Strings',
   'slug': 'returning-strings',
   'completedLanguages': ['clojure', 'csharp'],
   'completedAt': '2022-08-29T22:43:10.678Z'},
  {'id': '563089b9b7be03472d00002b',
   'name': 'Remove All The Marked Elements of a List',
   'slug': 'remove-all-the-marked-elements-of-a-list',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-29T22:23:10.773Z'},
  {'id': '57a0885cbb9944e24c00008e',
   'name': 'Remove exclamation marks',
   'slug': 'remove-exclamation-marks',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-29T22:05:33.716Z'},
  {'id': '52685f7382004e774f0001f7',
   'name': 'Human Readable Time',
   'slug': 'human-readable-time',
   'completedLanguages': ['csharp'],
   'completedAt': '2022-08-29T21:37:50.440Z'},
  {'id': '57a0556c7cb1f31ab3000ad7',
   'name': 'MakeUpperCase',
   'slug': 'makeuppercase',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-28T15:56:47.934Z'},
  {'id': '58649884a1659ed6cb000072',
   'name': 'Thinkful - Logic Drills: Traffic light',
   'slug': 'thinkful-logic-drills-traffic-light',
   'completedLanguages': ['csharp'],
   'completedAt': '2022-08-28T02:32:29.228Z'},
  {'id': '544675c6f971f7399a000e79',
   'name': 'Convert a String to a Number!',
   'slug': 'convert-a-string-to-a-number',
   'completedLanguages': ['csharp', 'python'],
   'completedAt': '2022-08-28T02:19:55.476Z'},
  {'id': '56dec885c54a926dcd001095',
   'name': 'Opposite number',
   'slug': 'opposite-number',
   'completedLanguages': ['python', 'csharp'],
   'completedAt': '2022-08-28T02:12:27.448Z'},
  {'id': '50ee6b0bdeab583673000025',
   'name': 'Basic variable assignment',
   'slug': 'basic-variable-assignment',
   'completedLanguages': ['python',
    'cobol',
    'c',
    'cpp',
    'coffeescript',
    'crystal',
    'csharp',
    'dart',
    'fsharp',
    'go',
    'groovy',
    'haskell',
    'java',
    'javascript',
    'julia',
    'php',
    'r',
    'racket',
    'typescript',
    'ruby',
    'scala'],
   'completedAt': '2022-08-27T17:10:03.132Z'},
  {'id': '546e2562b03326a88e000020',
   'name': 'Digit*Digit',
   'slug': 'digit-star-digit',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-27T03:26:16.532Z'},
  {'id': '52fba66badcd10859f00097e',
   'name': 'Disemvowel Trolls',
   'slug': 'disemvowel-trolls',
   'completedLanguages': ['csharp', 'python'],
   'completedAt': '2022-08-27T02:17:52.143Z'},
  {'id': '54ff3102c1bad923760001f3',
   'name': 'Vowel Count',
   'slug': 'vowel-count',
   'completedLanguages': ['csharp', 'cobol'],
   'completedAt': '2022-08-26T14:32:49.139Z'},
  {'id': '57e76bc428d6fbc2d500036d',
   'name': 'Convert a string to an array',
   'slug': 'convert-a-string-to-an-array',
   'completedLanguages': ['csharp', 'python'],
   'completedAt': '2022-08-26T13:39:51.023Z'},
  {'id': '57cc975ed542d3148f00015b',
   'name': 'You only need one - Beginner',
   'slug': 'you-only-need-one-beginner',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-26T01:42:42.092Z'},
  {'id': '511f0fe64ae8683297000001',
   'name': 'Basic Training: Add item to an Array',
   'slug': 'basic-training-add-item-to-an-array',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-26T01:22:33.022Z'},
  {'id': '56606694ec01347ce800001b',
   'name': 'Is this a triangle?',
   'slug': 'is-this-a-triangle',
   'completedLanguages': ['csharp'],
   'completedAt': '2022-08-26T00:31:43.054Z'},
  {'id': '55685cd7ad70877c23000102',
   'name': 'Return Negative',
   'slug': 'return-negative',
   'completedLanguages': ['python', 'c', 'cpp'],
   'completedAt': '2022-08-26T00:23:37.718Z'},
  {'id': '57eae65a4321032ce000002d',
   'name': 'Fake Binary',
   'slug': 'fake-binary',
   'completedLanguages': ['csharp', 'python'],
   'completedAt': '2022-08-25T19:21:41.793Z'},
  {'id': '5467e4d82edf8bbf40000155',
   'name': 'Descending Order',
   'slug': 'descending-order',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-25T17:29:27.893Z'},
  {'id': '54c27a33fb7da0db0100040e',
   'name': "You're a square!",
   'slug': 'youre-a-square',
   'completedLanguages': ['csharp'],
   'completedAt': '2022-08-25T17:15:29.066Z'},
  {'id': '53da3dbb4a5168369a0000fe',
   'name': 'Even or Odd',
   'slug': 'even-or-odd',
   'completedLanguages': ['python', 'csharp'],
   'completedAt': '2022-08-25T17:09:52.386Z'},
  {'id': '55f8a9c06c018a0d6e000132',
   'name': 'Regex validate PIN code',
   'slug': 'regex-validate-pin-code',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-25T00:48:55.238Z'},
  {'id': '55a2d7ebe362935a210000b2',
   'name': 'Find the smallest integer in the array',
   'slug': 'find-the-smallest-integer-in-the-array',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T23:30:42.563Z'},
  {'id': '551f37452ff852b7bd000139',
   'name': 'Binary Addition',
   'slug': 'binary-addition',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T22:13:39.254Z'},
  {'id': '5772da22b89313a4d50012f7',
   'name': 'Grasshopper - Personalized Message',
   'slug': 'grasshopper-personalized-message',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T22:09:46.940Z'},
  {'id': '53af2b8861023f1d88000832',
   'name': 'Are You Playing Banjo?',
   'slug': 'are-you-playing-banjo',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T15:48:55.355Z'},
  {'id': '57356c55867b9b7a60000bd7',
   'name': 'Basic Mathematical Operations',
   'slug': 'basic-mathematical-operations',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T15:32:22.687Z'},
  {'id': '54edbc7200b811e956000556',
   'name': 'Counting sheep...',
   'slug': 'counting-sheep-dot-dot-dot',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T15:21:37.638Z'},
  {'id': '53369039d7ab3ac506000467',
   'name': "Convert boolean values to strings 'Yes' or 'No'.",
   'slug': 'convert-boolean-values-to-strings-yes-or-no',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-24T15:05:41.837Z'},
  {'id': '514b92a657cdc65150000006',
   'name': 'Multiples of 3 or 5',
   'slug': 'multiples-of-3-or-5',
   'completedLanguages': ['csharp', 'python', 'javascript', 'c', 'clojure'],
   'completedAt': '2022-08-24T00:57:30.642Z'},
  {'id': '57d29ccda56edb4187000052',
   'name': 'Rock Paper Scissors Lizard Spock',
   'slug': 'rock-paper-scissors-lizard-spock',
   'completedLanguages': ['csharp'],
   'completedAt': '2022-08-23T23:55:49.473Z'},
  {'id': '5583090cbe83f4fd8c000051',
   'name': 'Convert number to reversed array of digits',
   'slug': 'convert-number-to-reversed-array-of-digits',
   'completedLanguages': ['python', 'csharp'],
   'completedAt': '2022-08-23T22:51:17.555Z'},
  {'id': '5266876b8f4bf2da9b000362',
   'name': 'Who likes it?',
   'slug': 'who-likes-it',
   'completedLanguages': ['python'],
   'completedAt': '2022-08-23T20:17:25.778Z'},
  {'id': '55b42574ff091733d900002f',
   'name': 'Friend or Foe?',
   'slug': 'friend-or-foe',
   'completedLanguages': ['csharp', 'python'],
   'completedAt': '2022-08-17T00:02:06.481Z'},
  {'id': '50654ddff44f800200000004',
   'name': 'Multiply',
   'slug': 'multiply',
   'completedLanguages': ['csharp',
    'python',
    'agda',
    'coq',
    'cpp',
    'clojure',
    'c',
    'crystal',
    'd',
    'coffeescript',
    'commonlisp',
    'dart',
    'cfml',
    'cobol',
    'elixir',
    'lambdacalc',
    'javascript',
    'riscv',
    'elm',
    'erlang',
    'factor',
    'forth',
    'ruby',
    'rust'],
   'completedAt': '2022-08-16T23:38:50.035Z'}]}

In [48]:
#creates a Series that has all of the students in the class

class_c = pd.Series(["Captain Quack",\
                       "Siddhi1",\
                       "Libin.",\
                       "ElliShep23",\
                       "mgamboa",\
                       "conorlowe23",\
                       "OmeedI",\
                       "bkampine",\
                       "ahmeda26",\
                       "MaxavierD",\
                       "mariotedeschi26@usn.org"
                      ])

class_h = pd.Series(["JoshJJJJJJJJJJJJJJ",\
                      "Christophernichols",\
                      "usnafo",\
                      "jacobnichols",\
                      "simonrosenblum143",\
                      "BeckettD",\
                      "hollysch",\
                      "gardnerharris",\
                      "cfrance14",\
                      "BryceCochran"
                      ])

In [58]:
printClassSummary(class_h)

            Name                User  Rank  Score  Completed
0         Josh J  JoshJJJJJJJJJJJJJJ  -5.0  298.0       67.0
1                 Christophernichols  -6.0  220.0       61.0
5                           BeckettD  -6.0  116.0       30.0
4                  simonrosenblum143  -6.0   98.0       25.0
2                             usnafo  -6.0   95.0       45.0
3                       jacobnichols  -6.0   81.0       36.0
6                           hollysch  -7.0   49.0       23.0
7        gardner       gardnerharris  -7.0   47.0       26.0
8  Collin France           cfrance14  -7.0   36.0       18.0
9        Bryce C        BryceCochran  -7.0   28.0       14.0

In [55]:
printOutSummary(class_c)

           Name                     User  Rank   Score  Completed
0   Mason Lack             Captain Quack  -3.0  2714.0      296.0
1                                Siddhi1  -6.0   121.0       36.0
4                                mgamboa  -7.0    66.0       28.0
3           ELS               ElliShep23  -7.0    62.0       39.0
7                               bkampine  -7.0    60.0       27.0
6                                 OmeedI  -7.0    57.0       27.0
5                            conorlowe23  -7.0    56.0       30.0
8                               ahmeda26  -7.0    52.0       25.0
10               mariotedeschi26@usn.org  -7.0    52.0       24.0
9                              MaxavierD  -7.0    51.0       26.0
2         Libin                   Libin.  -7.0    50.0       28.0

In [73]:
lresponse = getUserData("g964")

getJsonDetails(lresponse)

  Name  User  Rank  Score  Completed
0       g964    -1  13510       2644

NameError: name 'response' is not defined